### ISSUE TITLE
untitled~~~

### ISSUE THREAD

**Issue by ReStar0010** [pkbbkphey/arduino-3.5-lcd-drawing#1]
100%C++，果然是Arduino玩家，這是多久之前的小專案??

**Comment by ReStar0010** [comment]
對了，你可以多放點繪圖後的照片上來XD

**Comment by pkbbkphey** [comment]
這個是前天的小測試XD，註解打雙語好像太奇怪了

我應該可以放影片在YOUTUBE上，我也多放點照片~

**Comment by pkbbkphey** [comment]
但是我發現同一個資料夾中只能放一張照片，還是不要放這邊好了~  怕會太亂，有什麼方法可以避免嗎 ?

**Comment by ReStar0010** [comment]
抱歉我剛才看到啊!!!!
不過資料夾你好像已經解決了~~，如果你覺得亂可以傳連結給我哦~~!!
我問你哦??如果用這個面板來做個電子筆記本可行嗎??或是會是好用的東西嘛??

**Comment by pkbbkphey** [comment]
我覺得筆記本應該去用Issues右邊的wiki，不太確定能不能設為私人筆記，但是看很多人寫筆記都在那邊，可以試試
還是說放其實放google drive的連結在readme那邊好像也不錯欸，我放一下

**Comment by ReStar0010** [comment]
好阿!!!

**Comment by ReStar0010** [comment]
好觀看很多了，感謝分享(~~~
